name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt upgrade -y
      - name: Setup Conan
        uses: jwidauer/setup-conan@v1
      - name: Initialize profile
        run: sudo conan profile detect
      - name: Install Dependencies
        run: sudo conan install . --build=missing --conf tools.system.package_manager:mode=install
      - name: Configure CMake
        run: sudo cmake --preset conan-release
      - name: Build Project
        run: sudo cmake --build --preset conan-release
      - name: Run Unit Tests
        run: sudo ctest --preset conan-release
  
  test_install_on_linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt upgrade -y
      - name: Install Conan
        run: sudo pip install conan
      - name: Initialize profile
        run: sudo conan profile detect
      - name: Run install script
        run: sudo ./gimmeit.sh

  test_install_on_mac:
    name: Install on Mac
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Conan
        run: sudo python3 -m pip install conan
      - name: Initialize profile
        run: sudo conan profile detect
      - name: Run install script
        run: sudo ./gimmeit.sh
