name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
      - name: Install Conan
        run: sudo pip install --ignore-installed conan
      - name: Cache Conan Dependencies
        id: cache-conan
        uses: actions/cache@v4.2.3
        with:
          path: /root/.conan2
          key: conan-dir
      - if: ${{steps.cache-conan.outputs.cache-hit != 'true'}}
        name: Install Dependencies
        run: |
          sudo conan profile detect
          sudo conan install . --build=missing --conf tools.system.package_manager:mode=install
      - name: Build Project
        run: |
          sudo cmake --preset conan-release
          sudo cmake --build --preset conan-release
      - name: Run Unit Tests
        run: sudo ctest --preset conan-release
  
  test_install_on_linux:
    name: Install on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
      - name: Run install script
        run: sudo ./gimmeit.sh

  test_install_on_mac:
    name: Install on Mac
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
      - name: Run install script
        run: sudo ./gimmeit.sh
