name: Conan Build Script Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt update -y
    - run: sudo apt upgrade -y

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1
      with:
        version: 2.6
    - name: Initialize profile
      run: conan profile detect

    - name: Run install script
      run: ./gimmeit.sh

